"""empty message

Revision ID: 4a87a3635f48
Revises: fe7ecdca20fb
Create Date: 2019-04-23 10:05:12.440110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a87a3635f48'
down_revision = 'fe7ecdca20fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('imgpath', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'imgpath')
    # ### end Alembic commands ###
