"""empty message

Revision ID: 80c2ca45bc76
Revises: 0d0b28e8fd87
Create Date: 2019-04-23 14:22:01.967310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c2ca45bc76'
down_revision = '0d0b28e8fd87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('img_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('img_post',
    sa.Column('ipid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('imgpath', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ipid', name='img_post_pkey')
    )
    # ### end Alembic commands ###
