"""empty message

Revision ID: aa9446baa67e
Revises: 
Create Date: 2019-04-22 11:24:58.886062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9446baa67e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('creator', sa.String(length=50), nullable=True))
    op.drop_constraint('post_puid_fkey', 'post', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('post_puid_fkey', 'post', 'user', ['puid'], ['uid'])
    op.drop_column('post', 'creator')
    # ### end Alembic commands ###
